source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'rails-api'
gem 'spring', :group => :development
gem 'mysql2'
gem 'jquery-rails', '>= 1.0.12'
gem 'rdoc'
gem 'metainspector'
gem 'json'
gem 'kaminari'
gem 'will_paginate', '~> 3.0.0'
gem 'authlogic'#,  github: 'binarylogic/authlogic' , ref: 'e4b2990d6282f3f7b50249b4f639631aef68b939'
gem 'rack-ssl', :require => 'rack/ssl'
gem 'nifty-generators'
gem 'rails-i18n'
gem "private_pub"
gem 'mongoid'
gem 'bson_ext'
gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
gem 'thin'
gem 'tenacity'
gem 'htmlentities'
gem 'bcrypt'
gem 'scrypt'
gem 'sprockets' 
